# Generated by Django 3.0.7 on 2020-06-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200609_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='google',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tweeter',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
