# Generated by Django 3.0.7 on 2021-02-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200609_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_admin',
            field=models.BooleanField(default=False),
        ),
    ]
