# Generated by Django 3.0.7 on 2021-02-07 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_parentsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsprofile',
            name='position',
            field=models.CharField(blank=True, default='Parent', max_length=100),
        ),
    ]
