# Generated by Django 3.0.7 on 2021-03-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_parentsprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
