# Generated by Django 3.0.7 on 2021-03-27 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210327_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='google',
            new_name='user_email',
        ),
    ]
