# Generated by Django 3.0.7 on 2021-02-05 20:17

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20210205_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerylist',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, null=True, quality=75, size=[800, 530], upload_to='gallary_pics'),
        ),
    ]
