# Generated by Django 3.0.7 on 2021-02-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20210205_1517'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerylist',
            old_name='image',
            new_name='gallery_image',
        ),
    ]
