# Generated by Django 3.0.7 on 2021-03-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20210206_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerylist',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallerylist',
            name='pic_cat',
            field=models.CharField(choices=[('Event', 'Event'), ('Summer', 'Summer'), ('Future', 'Future'), ('Building', 'Building'), ('About', 'About'), ('Volunteers', 'Volunteers'), ('Youth Leadership', 'Youth Leadership'), ('Gallary', 'Gallary')], default='Gallary', max_length=30),
        ),
    ]
