# Generated by Django 3.0.7 on 2021-02-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='attachment',
            field=models.FileField(default='TEST', upload_to='newsletter/pdfs/'),
            preserve_default=False,
        ),
    ]
