# Generated by Django 3.0.7 on 2021-02-04 16:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallarylist',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[800, 530], upload_to='gallary_pics'),
        ),
    ]
