# Generated by Django 3.0.7 on 2021-02-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_gallarylist_date_upload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GallaryList',
        ),
    ]
