# Generated by Django 3.0.7 on 2021-02-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_parentsprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgFacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certifiedTeachers', models.IntegerField()),
                ('successfulKids', models.IntegerField()),
                ('happyParents', models.IntegerField()),
                ('awardsWon', models.IntegerField()),
            ],
        ),
    ]
