# Generated by Django 3.0.7 on 2021-02-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_orgfacts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgfacts',
            old_name='awardsWon',
            new_name='counts',
        ),
        migrations.RemoveField(
            model_name='orgfacts',
            name='certifiedTeachers',
        ),
        migrations.RemoveField(
            model_name='orgfacts',
            name='happyParents',
        ),
        migrations.RemoveField(
            model_name='orgfacts',
            name='successfulKids',
        ),
        migrations.AddField(
            model_name='orgfacts',
            name='facts_category',
            field=models.CharField(default='Certified Teachers', max_length=150),
            preserve_default=False,
        ),
    ]
