# Generated by Django 3.0.7 on 2021-03-02 21:25

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20210206_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Future',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, size=[500, 400], upload_to='future_pics')),
                ('Overview', models.TextField(blank=True, max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('duration', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=0)),
            ],
        ),
    ]
