# Generated by Django 3.0.7 on 2021-03-03 18:33

from django.db import migrations, models
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_future'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 400], upload_to='youth_pics')),
                ('Overview', models.TextField(max_length=300)),
                ('content', tinymce.models.HTMLField()),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='future',
            name='Overview',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='future',
            name='duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='future',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='test', force_format='JPEG', keep_meta=True, quality=75, size=[500, 400], upload_to='future_pics'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='parentsprofile',
            name='user_parent',
            field=models.BooleanField(default=False),
        ),
    ]
