# Generated by Django 3.0.7 on 2021-03-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210303_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='future',
            old_name='Overview',
            new_name='overview',
        ),
        migrations.RenameField(
            model_name='youth',
            old_name='Overview',
            new_name='overview',
        ),
    ]
