# Generated by Django 3.0.7 on 2021-03-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_volunteers'),
    ]

    operations = [
        migrations.AddField(
            model_name='future',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
