# Generated by Django 3.0.7 on 2021-03-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_future_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsprofile',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='summer',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='volunteers',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='youth',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
