# Generated by Django 3.0.7 on 2021-03-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210319_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentsprofile',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
