# Generated by Django 3.0.7 on 2021-03-29 14:07

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_parentsprofile_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[500, 400], upload_to='future_pics'),
        ),
        migrations.AlterField(
            model_name='parentsprofile',
            name='parent_image',
            field=django_resized.forms.ResizedImageField(crop=None, default='default.jpg', force_format='JPEG', keep_meta=True, quality=75, size=[200, 200], upload_to='parent_pics'),
        ),
    ]
