# Generated by Django 3.0.7 on 2021-06-21 21:32

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0018_auto_20210412_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[500, 400], upload_to='future_pics'),
        ),
    ]
