# Generated by Django 3.0.7 on 2021-06-21 21:32

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0009_auto_20210327_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_posted2',
            field=models.DateField(blank=True, help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, default='2021-01-01', force_format='JPEG', keep_meta=True, quality=75, size=[800, 530], upload_to='post_pics'),
            preserve_default=False,
        ),
    ]
