# Generated by Django 3.0.7 on 2021-06-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0010_auto_20210621_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_posted2',
            new_name='event_date',
        ),
    ]
