# Generated by Django 3.0.7 on 2021-08-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20210621_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sort',
            field=models.IntegerField(default=999),
        ),
    ]
