# Generated by Django 3.0.7 on 2020-06-25 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfform', '0002_formpdf_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpdf',
            name='overview',
            field=models.CharField(max_length=400),
        ),
    ]
