# Generated by Django 3.0.7 on 2021-04-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfform', '0003_auto_20200624_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpdf',
            name='category',
            field=models.CharField(choices=[('future', 'FUTURE'), ('youth', 'YOUTH'), ('summer', 'SUMMER')], default='future', max_length=6),
        ),
    ]
