# Generated by Django 3.0.7 on 2021-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfform', '0004_formpdf_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpdf',
            name='category',
            field=models.CharField(choices=[('future', 'FUTURE'), ('youth', 'YOUTH'), ('summer', 'SUMMER'), ('others', 'OTHERS')], default='others', max_length=6),
        ),
    ]
