# Generated by Django 3.0.7 on 2021-08-07 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfform', '0005_auto_20210423_1306'),
        ('pdfform', '0005_auto_20210621_1732'),
    ]

    operations = [
    ]
